### ISSUE TITLE
Box formatting on Windows is broken

### ISSUE THREAD

**Issue by NybyDK** [atjn/AAU-P1-B226#37]
![image](https://user-images.githubusercontent.com/45389841/142840616-507b5b60-6bb8-4382-b19c-42fbc8de0e67.png)

**Comment by NybyDK** [comment]
also change decimals to only show maybe 2 decimals thank you :D

**Comment by atjn** [comment]
The decimals issue is fixed in #38

**Comment by NybyDK** [comment]
![image](https://user-images.githubusercontent.com/45389841/142998383-c6bb0829-677c-4441-bd0f-23719197f862.png)
windows print (after replacing stupid box thingies)
compared to correct linux print:
![image](https://user-images.githubusercontent.com/45389841/142998435-0b778286-6a33-42a2-8a7a-d8c78f8077bc.png)

**Comment by NybyDK** [comment]
> ![image](https://user-images.githubusercontent.com/45389841/142998383-c6bb0829-677c-4441-bd0f-23719197f862.png) windows print (after replacing stupid box thingies) compared to correct linux print: ![image](https://user-images.githubusercontent.com/45389841/142998435-0b778286-6a33-42a2-8a7a-d8c78f8077bc.png)

@atjn

**Comment by NybyDK** [comment]
it didn't do that weird thing before

**Comment by BaBrixx** [comment]
<img width="410" alt="Skærmbillede 2021-11-23 kl  10 30 20" src="https://user-images.githubusercontent.com/90306530/143000181-45aaf20e-b762-4b05-95a7-2de13e53f968.png">

@atjn Doesn't work on macOS either

**Comment by atjn** [comment]
wtf

**Comment by atjn** [comment]
Regarding the original formatting error, that seems to be because your terminal doesn't properly read unicode characters. The correct solution to that, is to fix your terminal, but I am also fine with just replacing the unicode characters with basic lines like you did. Does anyone else have opinions on this?

**Comment by NybyDK** [comment]
> Regarding the original formatting error, that seems to be because your terminal doesn't properly read unicode characters. The correct solution to that, is to fix your terminal, but I am also fine with just replacing the unicode characters with basic lines like you did. Does anyone else have opinions on this?

my opinion on this is that you should not bash my terminal for being different but be supportive of this lgbtq+ community of terminals... pls don't be so rude towards other terminals

**Comment by atjn** [comment]
> my opinion on this is that you should not bash my terminal for being different but be supportive of this lgbtq+ community of terminals... pls don't be so rude towards other terminals

I'm not the problem, your terminal is! It is so old and single minded that it doesn't even allow these chars to express themselves properly.

**Comment by NybyDK** [comment]
> I'm not the problem, your terminal is! It is so old and single minded that it doesn't even allow these chars to express themselves properly.

fuck
i go dtg now

**Comment by NybyDK** [comment]
![image](https://user-images.githubusercontent.com/45389841/143016185-2c93790e-d970-44d4-b716-a9b039cc5206.png)

**Comment by atjn** [comment]
Closed by #46
